# Generated by Django 3.2.8 on 2021-12-26 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=300)),
                ('album_genre', models.CharField(max_length=30)),
                ('album_cover', models.ImageField(upload_to='album_covers/')),
                ('album_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('cover', models.ImageField(upload_to='song_covers/')),
                ('is_single', models.BooleanField(default=False)),
                ('audio_file', models.FileField(upload_to='musics/', validators=[utils.validators.validate_is_audio])),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='songs.album')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
