# Generated by Django 3.2.8 on 2021-12-30 09:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_alter_music_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='uploaded_on',
            field=models.DateField(default=datetime.datetime(2021, 12, 30, 9, 39, 33, 723438, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='music',
            name='uploaded_on',
            field=models.DateField(default=datetime.datetime(2021, 12, 30, 9, 39, 33, 726436, tzinfo=utc)),
        ),
    ]
